---
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  # - name: Insert Index Page
  #   template:
  #     src: index.html
  #     dest: /usr/share/nginx/html/index.html

  - name: Create a configuration file for Mattermost
    template:
      src: templates/iptvserver.j2
      dest: /etc/nginx/conf.d/iptvserver
      owner: root
      group: root
      mode: 0664

  - name: Remove the existing default sites-enabled file.
    file:
      path: /etc/nginx/conf.d/default
      state: absent

  - name: Enable the mattermost configuration.
    file: 
      src: /etc/nginx/conf.d/iptvserver 
      dest: /etc/nginx/conf.d/default.conf 
      state: link

  - name: Start NGiNX
    service:
      name: nginx
      state: restarted
