---
      - name: Update APT package manager repositories cache
        become: true
        apt:
          update_cache: yes

      - name: Install pip
        apt: name=python-pip state=present

      - name: install docker-py
        pip: name=docker-py
          
      - name: Build Docker image from Dockerfile
        docker_image:
          name: iptvserver
          path: docker
          state: build
        
      - name: Running the container
        docker_container:
          image: iptvserver:latest
          path: docker
          state: running
            
      - name: Check if container is running
        shell: docker ps